### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#101]
@cb0806151 what is the way to force https on the website we are currently hosting? For typical websites hosted on something like GoDaddy or other web hosting solutions involving Cpanel it would typically be through .htaccess, can we do the same here or is it another config file that handles that?

**Comment by cb0806151** [comment]
@inflameous48 I looked into it and it doesn't sound that difficult (just adding a package to the frontend of the application). It could be a ticket tacked onto sprint 4 without adding much required effort

**Comment by inflameous48** [comment]
@cb0806151 just saw that you responded to this one, let's definitely make this a bit of a priority. If things add up too much onto a sprint, definitely let us know and we can change it.

**Comment by cb0806151** [comment]
@inflameous48 added [this package](https://github.com/nuxt-contrib/redirect-ssl) to force https on production and merged and deployed the changes so you should see it when you navigate to the pages
