### ISSUE TITLE
Add a sitemap

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#44]

**Comment by cb0806151** [comment]
@inflameous48 can I get some more context on what is the desired result of this ticket?

**Comment by inflameous48** [comment]
@cb0806151 a sitemap is like a document for search engines where they can find all the links from a website and it also dictates how often the search engine crawler should re-crawl the page for new information. Here's an example of what it looks like https://www.canyoudrinktapwaterin.com/sitemap_index.xml

This one is generated by a Wordpress plugin, every time you add a new page/post it adds that one to the sitemap, we would want something similar. 

Here's an example of a sitemap that we would be striving for https://www.yelpreservations.com/sitemap.xml

`<url>
<loc>https://www.seatme.com/</loc>
<lastmod>2013-04-05</lastmod>
<changefreq>monthly</changefreq>
<priority>1</priority>
</url>`

this is what adding a page to the sitemap would look like structure-wise, and here is the documentation for each of those tags https://www.sitemaps.org/protocol.html (scroll down the page)

**Comment by inflameous48** [comment]
@cb0806151 this one seems to have http links, since we use an SSL certificate, the default website view is https://www.wodeveryday.com/, would it be possible to change it to this version?
