### ISSUE TITLE
Update Site Title

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#45]
update the site title with the following structure 
<page name> | WOD Every Day

For the homepage, we would have:
Find a Gym Anywhere | WOD Every Day

For state/country/city pages:
The Best Gyms in <state/city/country> | WOD Every Day
example: The Best Gyms in Houston | WOD Every Day

For individual gym page:
<gym name> | WOD Every Day

**Comment by cb0806151** [comment]
@inflameous48 just to verify, you want the individual gym pages to just be "| WOD Every Day"? No gym name or anything

**Comment by inflameous48** [comment]
@cb0806151 oops, my bad, it's supposed to say "{gym name} | WOD Every Day" thanks for pointing that out

**Comment by ezl** [comment]
@inflameous48 the capitalization on the title doesn't seem to match your ticket values. is this ok? or should we make it use Title Casing as you specified?

**Comment by inflameous48** [comment]
@ezl this appears to be fixed now
