### ISSUE TITLE
Managing Meta Tags

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#49]
We need a system to be able to manage the following:

1. Page Title
2. Meta Description
3. Schema
4. Open Graph Tags
5. Alt Tags

**Comment by cb0806151** [comment]
Hey @inflameous48 what would be the appropriate tags to set and what values should they contain for each individual page?

**Comment by inflameous48** [comment]
@cb0806151 I have closed this ticket in order to expand on each of these separately, meta title already falls under the page title ticket, so that is the same thing

**Comment by inflameous48** [comment]
@cb0806151 I'm reopening this and edited it so that we can have a system to manage the tags for individual pages if we want to do so.

**Comment by cb0806151** [comment]
@inflameous48 can you expound upon what you mean by a system for managing tags for individual pages? Have you already seen such a system in action and would like to replicate it in this application?

**Comment by inflameous48** [comment]
@cb0806151 not sure if I've seen it in action, Wordpress has something like this. Basically we have the default meta description template for each map, but if we wanted to overwrite that, we would do that by adding manually inputting the data. Priority would be to have these done:

- Page Title
- Meta Description
- Schema
- Open Graph Tags

Not sure how difficult it would be to do that for the alt tags, but that's not a priority

**Comment by cb0806151** [comment]
@inflameous48 so essentially an admin page where you could set those four attributes for any page in the website?

**Comment by inflameous48** [comment]
@cb0806151 yeah, that would basically be it.

**Comment by cb0806151** [comment]
@inflameous48 alright then how soon do we need this by?

Why I'm asking is because when this ticket got closed I factored it out of both my time and pricing estimates. I can factor it back into this sprint but I'll have to up the price and the time needed. Could we move it back into `upcoming` and add it to sprint 4 or a later sprint?

**Comment by inflameous48** [comment]
@cb0806151 that is fair, you can move it back to upcoming
