### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#56]
add a footer that will later on include things like TOS, Privacy, Social Media Links

**Comment by inflameous48** [comment]
@cb0806151 let's use the following layout for the footer

![image](https://user-images.githubusercontent.com/50846999/83959613-a295d080-a887-11ea-8ed4-95edb4d317d8.png)

For links, leave those there, just don't link them yet. For social icons, please add facebook and Instagram, those don't have to link anywhere as well.

Please add the following before everything "CrossFit® is a registered trademark of CrossFit, Inc. This website is not endorsed, sponsored, or affiliated with CrossFit, Inc."

**Comment by ezl** [comment]
@inflameous48 footer exists, but now there are dead social media links.

1. do you want that as is with dead links?
2. do you want to remove them?
3. do you want to create the actual social media pages then link them?
