### ISSUE TITLE
Schema Markup

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#61]
The Shema mark-up snippet should be placed in the <header> tags of the website and we are going to use the following structure for the markup

`<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "ExerciseGym",
  "name": "{gym name}",
  "image": "{gym logo}",
  "@id": "{gym page url}",
  "telephone": "{gym phone}",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "{gym address}",
    "postalCode": "{gym postal code}",
    "addressCountry": "{gym code}"
  } 
}
</script>`

**Comment by cb0806151** [comment]
@inflameous48 are we just going to be using this on the gyms pages or will there be another schema for the geography pages?

**Comment by inflameous48** [comment]
@cb0806151 right now only for the gyms

**Comment by cb0806151** [comment]
Caveat: The phone number for a gyms isn't displayed with the schema markup information yet; this information needs to be fetched before the html is generated and so will be added after task #79 is finished
