### ISSUE TITLE
Meta Description

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#62]
Meta Description for the homepage:

"WOD Every Day is the Largest Platform for CrossFit Gyms Across the World. Get The Latest Reviews, Pricing, Contact Information for CrossFit Gyms in Your Area."

Meta Description for the city location pages:
"The {number of gyms in city} Best CrossFit Gyms in {city}. Check Out The Latest Reviews, Pricing, Contact Information for CrossFit Gyms in {city}"

Meta Description for individual gym pages:
"{number of reviews} for {gym name}. Photos, Pricing, Contact Information and All You Need To Know Before Visiting"

**Comment by cb0806151** [comment]
@inflameous48 something that you should be aware of; google only allows you to retrieve a maximum of five reviews from a location, so the number of reviews will always be less than or equal too five

**Comment by cb0806151** [comment]
@inflameous48 should there be a default meta description for the rest of the pages? (country search and state search)

**Comment by cb0806151** [comment]
in their current state they'll leave the og tags with a blank description when linked to

**Comment by inflameous48** [comment]
@cb0806151 let's do the following

**For countries:**
"{nr of gyms in that country} across {nr of cities that have gym CrossFit gyms}. Find the best CrossFit Gym in your City. Photos, Pricing, Contact Information and All You Need To Know Before Visiting"

**For states:**
"{nr of gyms in that state} across {nr of cities that have gym CrossFit gyms}. Find the best CrossFit Gym in your City. Photos, Pricing, Contact Information and All You Need To Know Before Visiting"

Regarding OG tags, if a page doesn't have a meta description, take the homepage description as the default one, this applies only to OG tags, for pages that don't have a meta description template, just leave it blank.

**Comment by cb0806151** [comment]
Caveat: The number of reviews for a gym page is not displayed yet; this information needs to be fetched before the html is generated and so will be added after task #79 is finished

**Comment by inflameous48** [comment]
@cb0806151 I can see that this included in the source page, but is behind some sort of NUXT function, I think the issue here might be that search engines wouldn't be able to read it, the typical way for these to be displayed is inside the <head> tag and following this format:

<meta name="description"  content="This is an example of a meta description. This will often show up in search results.">

**Comment by cb0806151** [comment]
@inflameous48 I think part of that message got clipped; which format are you specifying?

**Comment by cb0806151** [comment]
It appears to be showing up when running a meta tag description test.

I'm entering https://www.wodeveryday.com/gym/crossfit-pantheon into https://seositecheckup.com/tools/meta-description-test and its passing

**Comment by inflameous48** [comment]
@cb0806151 interesting, so I've checked this with another tool and I didn't get the same results, I assume because the tool doesn't process javascript and cannot read it. From my knowledge search engines can process the meta description from the page so I'm moving this to complete.
