### ISSUE TITLE
OG Tags

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#63]
We are going to have the main 3 elements here, title, description and image. The title and description can be used the same as the page title and meta description, for the image we will use the gym logo or the first image if there's no image for that logo.

**Comment by cb0806151** [comment]
@inflameous48 just to verify these tags will be exclusive to the gym pages right? We don't really have images on any of the other pages yet, except for city, and there are multiple different images on the city page (I suppose eventually we could have the website logo as the image for the geographic pages)

**Comment by inflameous48** [comment]
@cb0806151 this will apply to all pages, for non-gym pages we are going to use a single image, perhaps the logo

**Comment by cb0806151** [comment]
@inflameous48 for these og tags do we just want facebook or twitter as well?

**Comment by inflameous48** [comment]
@cb0806151 hmm, I thought those are universal, does twitter have separate tags? I think they use the same tags. I will look into it.

**Comment by inflameous48** [comment]
@cb0806151 according to facebook debugger looks like we might need the 'og:image:width' and 'og:image:height' tags as well in order of the og:image to display, could you just set those as the native resolutions for each of the images?

**Comment by cb0806151** [comment]
@inflameous48 I've submitted a fix for this; however, I can't test to see if its working as every link I submit now doesn't show the error message you mentioned above

**Comment by inflameous48** [comment]
@ezl this seems to work now, although there are a few false-positives from Facebook, the first time I debug a new page, it works all fine and shows the image, but if I debug it a 2nd time, it says that those tags ('og:image:width' and 'og:image:height') are missing

**Comment by inflameous48** [comment]
On other applications, it seems to load the image just fine, so I would consider this complete
